In [34]:
import pandas as pd
from calendar import isleap

In [35]:
# future data
data = pd.read_csv('Price - After ES.csv', header=0, skiprows=[1], index_col=0)
data.head()

,2030,2031,2032,2033,2034,2035,2036,2037,2038,2039,...,2051,2052,2053,2054,2055,2056,2057,2058,2059,2060
Hour,,,,,,,,,,,,,,,,,,,,,
1,33.86,31.04,28.43,25.76,23.17,20.50,17.92,15.15,11.92,9.89,...,-29.71,-33.35,-37.11,-40.76,-44.45,-48.08,-51.82,-55.41,-59.13,-62.79
2,33.86,31.03,28.40,25.77,23.17,20.42,17.92,15.13,11.92,9.91,...,-29.77,-33.46,-37.13,-40.80,-44.42,-48.11,-51.82,-55.45,-59.13,-62.84
3,33.86,31.04,28.36,25.77,23.18,20.41,17.91,15.13,11.84,9.84,...,-29.77,-33.43,-37.14,-40.78,-44.46,-48.07,-51.80,-55.60,-59.13,-62.83
4,33.86,31.03,28.36,25.78,23.18,20.41,17.91,15.14,11.84,9.82,...,-29.75,-33.45,-37.14,-40.76,-44.48,-48.07,-51.79,-55.51,-59.34,-62.81
5,33.86,31.03,28.36,25.77,23.17,20.42,17.91,15.13,11.88,9.83,...,-29.78,-33.43,-37.12,-40.79,-44.46,-48.10,-51.78,-55.61,-59.32,-62.79

In [41]:
dfs = []
for year in data:
    df = data[[year]].copy()
    df.index = pd.date_range(start=year + '-01-01', periods=len(df), freq='H')
    df['Hour'] = df.index.hour + 1
    df.index = [pd.Timestamp(r.strftime('%Y-%m-%d')) for r in df.index]
    df = df.pivot(columns='Hour', values=year)
    if isleap(int(year)):
        last_day = pd.Timestamp(int(year), 12, 31)
        last_row = df.iloc[-1]
        last_row.name = last_day
        df = df.append(last_row)
    df.index.name = 'Date'
    dfs.append(df)
df = pd.concat(dfs, axis=0)

In [42]:
df.to_csv('./future_prices_pivoted.csv')